"""Add enhanced property data fields

Revision ID: 2d698ae298be
Revises: 7101f43e4767
Create Date: 2026-02-10 09:11:41.547314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d698ae298be'
down_revision: Union[str, Sequence[str], None] = '7101f43e4767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('construction_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('property_subtype', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('has_garden', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('has_parking', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('has_balcony', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('has_garage', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('agent_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('agent_phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('agent_email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('agency_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('listing_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('days_on_market', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('days_on_market')
        batch_op.drop_column('listing_date')
        batch_op.drop_column('agency_name')
        batch_op.drop_column('agent_email')
        batch_op.drop_column('agent_phone')
        batch_op.drop_column('agent_name')
        batch_op.drop_column('has_garage')
        batch_op.drop_column('has_balcony')
        batch_op.drop_column('has_parking')
        batch_op.drop_column('has_garden')
        batch_op.drop_column('property_subtype')
        batch_op.drop_column('construction_type')

    # ### end Alembic commands ###
